#pragma once

#include "tag-version.h"

enum potion_type
{
    POT_CURING,
    POT_HEAL_WOUNDS,
    POT_HASTE,
    POT_MIGHT,
    POT_BRILLIANCE,
    POT_AGILITY,
    POT_GAIN_STRENGTH,
    POT_GAIN_DEXTERITY,
    POT_GAIN_INTELLIGENCE,
    POT_AMNESIA,
    POT_POISON,
    POT_SLOWING,
    POT_CANCELLATION,
    POT_AMBROSIA,
    POT_INVISIBILITY,
#if TAG_MAJOR_VERSION == 34
    POT_PORRIDGE,
#endif
    POT_DEGENERATION,
    POT_DECAY,
    POT_WATER,
    POT_EXPERIENCE,
    POT_MAGIC,
#if TAG_MAJOR_VERSION == 34
    POT_RESTORE_ABILITIES,
    POT_STRONG_POISON,
#endif
    POT_BERSERK_RAGE,
    POT_CURE_MUTATION,
    POT_MUTATION,
    POT_RESISTANCE,
    POT_BLOOD,
#if TAG_MAJOR_VERSION == 34
    POT_BLOOD_COAGULATED,
#endif
    POT_LIGNIFY,
    POT_BENEFICIAL_MUTATION,
    NUM_POTIONS
};

// used for objstat
const vector<potion_type> potion_types =
{
    POT_GAIN_STRENGTH,
    POT_GAIN_DEXTERITY,
    POT_GAIN_INTELLIGENCE,
    POT_CURING,
    POT_HEAL_WOUNDS,
    POT_HASTE,
    POT_MIGHT,
    POT_BRILLIANCE,
    POT_AMNESIA,
    POT_CANCELLATION,
    POT_AMBROSIA,
    POT_INVISIBILITY,
    POT_DEGENERATION,
    POT_DECAY,
    POT_WATER,
    POT_BLOOD,
    POT_EXPERIENCE,
    POT_MAGIC,
    POT_BERSERK_RAGE,
    POT_CURE_MUTATION,
    POT_MUTATION,
    POT_BENEFICIAL_MUTATION,
    POT_RESISTANCE,
    POT_LIGNIFY,
    POT_POISON,
    POT_SLOWING,

};

#if TAG_MAJOR_VERSION == 34
#define CASE_REMOVED_POTIONS(pot) \
case POT_PORRIDGE: \
case POT_RESTORE_ABILITIES: \
case POT_STRONG_POISON: \
case POT_BLOOD_COAGULATED: \
{ \
    die("Removed potion type %d!", static_cast<int>(pot)); \
}
#else
#define CASE_REMOVED_POTIONS(pot)
#endif
